<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Peserta_model extends CI_Model
{

    public $table = 'peserta';
    public $id = 'nopeserta';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nopeserta,namapeserta,tempatlahir,tanggallahir,jeniskelamin,suku,pilihan1,pilihan2,pilihan3,jenjangslta,jurusanslta,tahunlulus,asalslta,nbahasa,nipa,nips,nverbal,status,tahunakademik');
        $this->datatables->from('peserta');
        //add this line for join
        //$this->datatables->join('table2', 'peserta.field = table2.field');
        
        $this->datatables->add_column('action', '<a href="'.site_url('peserta/update/$1').'" class="btn btn-info btn-sm btn-flat">Edit</a> <a href="javascript:void(0);" class="delete_record btn btn-danger btn-sm btn-flat" data-code="$1">Hapus</a>', 'nopeserta');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nopeserta', $q);
	$this->db->or_like('namapeserta', $q);
	$this->db->or_like('tempatlahir', $q);
	$this->db->or_like('tanggallahir', $q);
	$this->db->or_like('jeniskelamin', $q);
	$this->db->or_like('suku', $q);
	$this->db->or_like('pilihan1', $q);
	$this->db->or_like('pilihan2', $q);
	$this->db->or_like('pilihan3', $q);
	$this->db->or_like('jenjangslta', $q);
	$this->db->or_like('jurusanslta', $q);
	$this->db->or_like('tahunlulus', $q);
	$this->db->or_like('asalslta', $q);
	$this->db->or_like('nbahasa', $q);
	$this->db->or_like('nipa', $q);
	$this->db->or_like('nips', $q);
	$this->db->or_like('nverbal', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tahunakademik', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nopeserta', $q);
	$this->db->or_like('namapeserta', $q);
	$this->db->or_like('tempatlahir', $q);
	$this->db->or_like('tanggallahir', $q);
	$this->db->or_like('jeniskelamin', $q);
	$this->db->or_like('suku', $q);
	$this->db->or_like('pilihan1', $q);
	$this->db->or_like('pilihan2', $q);
	$this->db->or_like('pilihan3', $q);
	$this->db->or_like('jenjangslta', $q);
	$this->db->or_like('jurusanslta', $q);
	$this->db->or_like('tahunlulus', $q);
	$this->db->or_like('asalslta', $q);
	$this->db->or_like('nbahasa', $q);
	$this->db->or_like('nipa', $q);
	$this->db->or_like('nips', $q);
	$this->db->or_like('nverbal', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tahunakademik', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete()
    {
        $nopeserta=$this->input->post('nopeserta');
        $this->db->where('nopeserta',$nopeserta);
        $result=$this->db->delete($this->table);
        return $result;
    }

    public function get_last_id(){
        $query = $this->db->get('peserta');
        $row = $query->last_row();
        return $row->nopeserta+1;
    } 

    

}

/* End of file Peserta_model.php */
/* Location: ./application/models/Peserta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-13 15:16:41 */
/* http://harviacode.com */